include:
  - compose/databases.yaml
  - compose/applications.yaml
  - compose/observability.yaml

networks:
  microservices-observability-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
  prometheus_data:
  grafana_data:
  tempo_data:
  loki_data:
  alertmanager_data: