services:


  config-server:
    container_name: ms_config-server
    build:
      context: ./services/config-server
      dockerfile: ../../docker/config/Dockerfile
    restart: unless-stopped
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8888/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 15s
    networks:
      - microservices-observability-net

  discovery-service:
    container_name: ms_discovery-service
    build:
      context: ./services/discovery
      dockerfile: ../../docker/discovery/Dockerfile
    restart: unless-stopped
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - microservices-observability-net

  customer-service:
    container_name: ms_customer-service
    build:
      context: ./services/customer
      dockerfile: ../../docker/customer/Dockerfile
    restart: unless-stopped
    ports:
      - "8090:8090"
    depends_on:
      config-server:
        condition: service_healthy
      mongodb:
        condition: service_started
      discovery-service:
        condition: service_started
    networks:
      - microservices-observability-net
  product-service:
    container_name: ms_product-service
    build:
      context: ./services/product
      dockerfile: ../../docker/product/Dockerfile
    restart: unless-stopped
    ports:
      - "8063:8063"
    depends_on:
      config-server:
        condition: service_healthy
      postgresql:
        condition: service_healthy
      discovery-service:
        condition: service_started
    networks:
      - microservices-observability-net


  postgresql:
    container_name: ms_postgresql
    image: postgres:18.4
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - microservices-observability-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PFAMIN_DEFAULT_PASSWORD:-admin}

    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

    depends_on:
      - postgresql

    networks:
      - microservices-observability-net

    restart: unless-stopped

  mongodb:
    image: mongo:8.3
    container_name: ms_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - microservices-observability-net
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: ms_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongodb:27017/admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - microservices-observability-net
    depends_on:
      - mongodb

networks:
  microservices-observability-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
