services:

  config-server:
    container_name: ms_config-server
    build:
      context: ./services/config-server
      dockerfile: ../../docker/config/Dockerfile
    restart: unless-stopped
    ports:
      - "8888:8888"
    networks:
      - microservices-observability-net


  postgresql:
    container_name: ms_postgresql
    image: postgres:18.4
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: microservices
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-observability-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PFAMIN_DEFAULT_PASSWORD:-admin}

    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

    depends_on:
      - postgresql

    networks:
      - microservices-observability-net

    restart: unless-stopped

  mongodb:
    image: mongo:8.3
    container_name: ms_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - microservices-observability-net
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: ms_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongodb:27017/admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - microservices-observability-net
    depends_on:
      - mongodb

networks:
  microservices-observability-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
