spring:
  main:
    log-startup-info: false
    banner:
      mode: off

eureka:
  instance:
    hostname: discovery-service

  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761

logging:
  structured:
    format:
      console: logstash
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
    com.netflix.discovery: WARN
    com.husseinabonoktah: INFO

