spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/order
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: false
  cloud:
    openfeign:
      micrometer:
        enabled: true

application:
  config:
    customer-url: http://customer-service:8090/api/v1/customers
    product-url: http://product-service:8063/api/v1/products
    payment-url: http://payment-service:8092/api/v1/payments
  http:
    connect-timeout-ms: 3000
    read-timeout-ms: 5000
server:
  port: 8070


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}



management:
  server:
    port: 7075

  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus"


  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
      access: read_only
  info:
    env:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

  otlp:
    metrics:
      export:
        enabled: false

  tracing:
    sampling:
      probability: 1.0  # collect all traces, 0.1 collect 10% of traces

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://otel-collector:4318/v1/traces

info:
  app:
    name: ${spring.application.name}
    description: Order Service for microservices system Observability
    version: 1.0.0
    owner: Hussein Abo Noktah
