spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/payment
    username: root
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  main:
    log-startup-info: false
    banner:
      mode: off

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}

server:
  port: 8092

management:
  server:
    port: 7077

  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus"


  endpoint:
    health:
      show-components: when_authorized
      probes:
        enabled: true
      access: read_only
  info:
    env:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

  otlp:
    metrics:
      export:
        enabled: false


  tracing:
    sampling:
      probability: 1.0  # collect all traces, 0.1 collect 10% of traces

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://otel-collector:4318/v1/traces
  logging:
    export:
      enabled: true



logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
    com.netflix.discovery: WARN
    com.husseinabonoktah: INFO


info:
  app:
    name: ${spring.application.name}
    description: Payment Service for microservices system Observability
    version: 1.0.0
    owner: Hussein Abo Noktah
