CREATE TABLE category (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255)
);

CREATE TABLE product (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    available_quantity DOUBLE PRECISION NOT NULL,
    price NUMERIC(38, 2) NOT NULL,
    category_id INTEGER NOT NULL,
    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id)
        REFERENCES category (id)
);

CREATE INDEX idx_product_category_id ON product (category_id);
