services:
  prometheus:
    image: prom/prometheus:v3.11.3
    container_name: prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - ./../observability/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

    depends_on:
      - gateway-service
      - order-service
      - customer-service
      - payment-service
      - product-service
    networks:
      - microservices-observability-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:main-distroless-slim
    container_name: grafana_container
    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./../observability/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - microservices-observability-net
    restart: unless-stopped


  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel_collector_container
    command: ["--config=/etc/otel-collector.yml"]
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./../observability/otel-collector/otel-collector.yml:/etc/otel-collector.yml
    depends_on:
      - tempo
    networks:
      - microservices-observability-net
    restart: unless-stopped

  tempo:
    image: grafana/tempo:latest
    container_name: tempo_container
    command: [ "-config.file=/etc/tempo.yml" ]
    ports:
      - "3200:3200"
    volumes:
      - ./../observability/tempo/tempo.yml:/etc/tempo.yml
      - tempo_data:/var/tempo
    networks:
      - microservices-observability-net
    restart: unless-stopped

