spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configrations
  main:
    log-startup-info: false
    banner:
      mode: off

server:
  port: 8888

logging:
  structured:
    format:
      console: logstash
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
    com.netflix.discovery: WARN
    com.husseinabonoktah: INFO
